"""Alembic-based migration runner for clawtion.

Provides programmatic ``run_migrations`` and ``check_migration_status``
functions that can be called from the application entrypoint rather than
relying on the ``alembic`` CLI.
"""

from __future__ import annotations

import contextlib
import io
import logging
import os
from pathlib import Path

from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory

logger = logging.getLogger(__name__)

_PROJECT_ROOT: Path | None = None


def _find_project_root() -> Path:
    """Walk up from this file to locate the project root (where ``alembic/`` lives)."""
    global _PROJECT_ROOT
    if _PROJECT_ROOT is not None:
        return _PROJECT_ROOT

    current = Path(__file__).resolve().parent  # core/db/
    for _ in range(10):
        if (current / "alembic").is_dir() and (current / "alembic" / "env.py").is_file():
            _PROJECT_ROOT = current
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    # Fallback to environment variable or CWD.
    env_root = os.environ.get("CLAWTION_PROJECT_ROOT")
    if env_root:
        _PROJECT_ROOT = Path(env_root).resolve()
        return _PROJECT_ROOT
    _PROJECT_ROOT = Path.cwd().resolve()
    return _PROJECT_ROOT


def _make_alembic_config(db_url: str) -> Config:
    """Build an :class:`Alembic Config` pointing at the project's ``alembic/`` directory.

    Since there is no ``alembic.ini`` checked in, we configure the object
    entirely in code.
    """
    project_root = _find_project_root()
    alembic_dir = project_root / "alembic"

    alembic_cfg = Config()
    alembic_cfg.set_main_option("script_location", str(alembic_dir))
    alembic_cfg.set_main_option("sqlalchemy.url", db_url)
    # Suppress fileConfig (no .ini file).
    alembic_cfg.set_section_option("loggers", "keys", "root")
    return alembic_cfg


async def run_migrations(db_url: str) -> None:
    """Run all pending Alembic migrations against *db_url*.

    This is the programmatic equivalent of ``alembic upgrade head``.

    Args:
        db_url: Full database URL
            (e.g. ``postgresql+asyncpg://user:pass@localhost:5432/db``).

    Raises:
        MigrationError: If any migration step fails.
    """
    cfg = _make_alembic_config(db_url)
    try:
        logger.info("Running database migrations ...")
        command.upgrade(cfg, "head")
        logger.info("Migrations complete.")
    except Exception as exc:
        raise MigrationError(
            f"Migration failed for {db_url!r}: {exc}",
        ) from exc


async def check_migration_status(db_url: str) -> str:
    """Return a human-readable migration status string.

    Possible return values:

    * ``"up-to-date"`` — all migrations have been applied.
    * ``"behind"`` — there are pending migrations.
    * ``"no-migrations"`` — no revision scripts exist.
    * ``"error: <detail>"`` — something went wrong while checking.

    Args:
        db_url: Full database URL.
    """
    cfg = _make_alembic_config(db_url)
    script = ScriptDirectory.from_config(cfg)

    heads = script.get_heads()
    if not heads:
        return "no-migrations"

    try:
        stdout = io.StringIO()
        with contextlib.redirect_stdout(stdout):
            command.current(cfg, verbose=True)
        output = stdout.getvalue()
        # If "Current revision(s)" line shows "head" for all branches.
        if "head" not in output and "(head)" not in output:
            return "behind"
        return "up-to-date"
    except Exception as exc:
        return f"error: {exc}"


async def stamp_head(db_url: str) -> None:
    """Stamp the database as having all migrations applied (without running them).

    Useful for initial setup when the database schema already matches or
    when you want to mark the current state without executing SQL.

    Args:
        db_url: Full database URL.

    Raises:
        MigrationError: If the stamp operation fails.
    """
    cfg = _make_alembic_config(db_url)
    try:
        logger.info("Stamping database at head ...")
        command.stamp(cfg, "head")
        logger.info("Stamp complete.")
    except Exception as exc:
        raise MigrationError(
            f"Stamping failed for {db_url!r}: {exc}",
        ) from exc


async def create_revision(db_url: str, message: str, *, autogenerate: bool = False) -> str:
    """Create a new (empty or autogenerated) Alembic revision.

    The revision file is written to the ``alembic/versions/`` directory.

    Args:
        db_url: Full database URL.
        message: Short description for the revision.
        autogenerate: If True, compare the database schema against the
            ORM models and populate the migration script automatically.

    Returns:
        The revision identifier string (short hash).

    Raises:
        MigrationError: If the revision cannot be created.
    """
    cfg = _make_alembic_config(db_url)
    try:
        rev = command.revision(cfg, message=message, autogenerate=autogenerate)
        return rev.revision  # type: ignore[union-attr]
    except Exception as exc:
        raise MigrationError(
            f"Failed to create revision for {db_url!r}: {exc}",
        ) from exc


class MigrationError(Exception):
    """Raised when a migration operation fails."""
